using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OrderSolution.Domain.Entities
{
    public class Order
    {
        public int Id { get; set; }  // Auto-generated by the database
        public List<OrderItem> Items { get; private set; } = new List<OrderItem>();

        public void AddItem(OrderItem item)
        {
            Items.Add(item);
        }
    }
}
