#version: '3.8'

services:
  distribuitioncenterapi:
    container_name: distribuitioncenterapi
    hostname: distribuitioncenterapi
    build:
      context: ./DistribuitionCenterSolution/DistribuitionCenter.API
      dockerfile: /Dockerfile
    networks:
      - default
        #aliases:
          #- distribuitioncenterapi
    ports:
      - "5000:5000"
      # - "5001:5001"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
    depends_on:
      - jaeger

  orderapi:
    container_name: orderapi
    hostname: orderapi
    build:
      context: ./Order
      dockerfile: /Dockerfile
    networks:
      - default
    ports:
      - "5002:5000"
      # - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:5002;https://+:5003
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PostgresConnection=Host=postgres;Database=OrderDB;Username=root;Password=password
      - Kafka__BootstrapServers=kafka:9092
      - distribuitioncenterapi__Host=http://distribuitioncenterapi
      - distribuitioncenterapi__Port:5000
      #- kafka__Topic=order-retry-topic
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - jaeger

  orderconsumer:
    build:
      context: ./OrderRetrySolution
      dockerfile: /Dockerfile
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresConnection=Host=postgres;Database=OrderDB;Username=root;Password=password
      - Kafka__BootstrapServers=kafka:9092
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - jaeger

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2182:2181" # Porta alternativa para Zookeeper
    networks:
      - default

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:29092
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE # Define INSIDE para comunicação interna entre brokers
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092" # Porta alternativa para Kafka
      - "9092:9092"   # Porta interna (usada por outros contêineres)
    networks:
      - default

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: OrderDB
    ports:
      - "5432:5432" # Porta alternativa para PostgreSQL
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Porta alternativa para PgAdmin4
    networks:
      - default

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"   # Porta para o tráfego de clientes com compactação de dados
      - "6831:6831/udp"   # Porta para o tráfego de clientes sem compactação
      - "6832:6832/udp"   # Porta para o tráfego de agentes sem compactação
      - "5778:5778"       # Porta para configuração remota
      - "16686:16686"     # Interface web para consulta
      - "14250:14250"     # Porta para gRPC do coletor
      - "14268:14268"     # Porta HTTP do coletor
      - "14269:14269"     # Porta para o health check
      - "9411:9411"       # Porta Zipkin para compatibilidade
    networks:
      - default

networks:
  default:
    name: my_network
    driver: bridge
